export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-[#171717] text-white">
      <div className="container mx-auto px-8 py-16 max-w-4xl">
        <h1 className="text-4xl font-bold mb-8">Privacy Policy</h1>

        <div className="prose prose-invert max-w-none">
          <p className="text-gray-400 text-sm mb-6">Last updated: August 12, 2025</p>

          <p className="text-gray-300 mb-6">
            This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your
            information when You use the Service and tells You about Your privacy rights and how the law protects You.
          </p>

          <p className="text-gray-300 mb-8">
            We use Your Personal data to provide and improve the Service. By using the Service, You agree to the
            collection and use of information in accordance with this Privacy Policy.
          </p>

          <h2 className="text-2xl font-bold mb-4 text-white">Interpretation and Definitions</h2>

          <h3 className="text-xl font-semibold mb-4 text-white">Interpretation</h3>
          <p className="text-gray-300 mb-6">
            The words of which the initial letter is capitalized have meanings defined under the following conditions.
            The following definitions shall have the same meaning regardless of whether they appear in singular or in
            plural.
          </p>

          <h3 className="text-xl font-semibold mb-4 text-white">Definitions</h3>
          <p className="text-gray-300 mb-4">For the purposes of this Privacy Policy:</p>
          <ul className="list-disc list-inside space-y-2 text-gray-300 mb-8">
            <li>
              <strong>Account</strong> means a unique account created for You to access our Service or parts of our
              Service.
            </li>
            <li>
              <strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with
              a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities
              entitled to vote for election of directors or other managing authority.
            </li>
            <li>
              <strong>Application</strong> refers to PullUP by IBX, the software program provided by the Company.
            </li>
            <li>
              <strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement)
              refers to IBX LLC, 418 Broadway Ste N, NY 12207.
            </li>
            <li>
              <strong>Country</strong> refers to: New York, United States
            </li>
            <li>
              <strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a
              digital tablet.
            </li>
            <li>
              <strong>Personal Data</strong> is any information that relates to an identified or identifiable
              individual.
            </li>
            <li>
              <strong>Service</strong> refers to the Application.
            </li>
            <li>
              <strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of
              the Company.
            </li>
            <li>
              <strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the
              Service or from the Service infrastructure itself.
            </li>
            <li>
              <strong>You</strong> means the individual accessing or using the Service, or the company, or other legal
              entity on behalf of which such individual is accessing or using the Service, as applicable.
            </li>
          </ul>

          <h2 className="text-2xl font-bold mb-4 text-white">Collecting and Using Your Personal Data</h2>

          <h3 className="text-xl font-semibold mb-4 text-white">Types of Data Collected</h3>

          <h4 className="text-lg font-semibold mb-3 text-white">Personal Data</h4>
          <p className="text-gray-300 mb-4">
            While using Our Service, We may ask You to provide Us with certain personally identifiable information that
            can be used to contact or identify You. Personally identifiable information may include, but is not limited
            to:
          </p>
          <ul className="list-disc list-inside space-y-1 text-gray-300 mb-6">
            <li>Email address</li>
            <li>First name and last name</li>
            <li>Usage Data</li>
          </ul>

          <h4 className="text-lg font-semibold mb-3 text-white">Usage Data</h4>
          <p className="text-gray-300 mb-4">Usage Data is collected automatically when using the Service.</p>
          <p className="text-gray-300 mb-6">
            Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address),
            browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the
            time spent on those pages, unique device identifiers and other diagnostic data.
          </p>

          <h4 className="text-lg font-semibold mb-3 text-white">Information Collected while Using the Application</h4>
          <p className="text-gray-300 mb-4">
            While using Our Application, in order to provide features of Our Application, We may collect, with Your
            prior permission:
          </p>
          <ul className="list-disc list-inside space-y-1 text-gray-300 mb-6">
            <li>Information from your Device's phone book (contacts list)</li>
            <li>Pictures and other information from your Device's camera and photo library</li>
          </ul>

          <h3 className="text-xl font-semibold mb-4 text-white">Use of Your Personal Data</h3>
          <p className="text-gray-300 mb-4">The Company may use Personal Data for the following purposes:</p>
          <ul className="list-disc list-inside space-y-2 text-gray-300 mb-8">
            <li>
              <strong>To provide and maintain our Service</strong>, including to monitor the usage of our Service.
            </li>
            <li>
              <strong>To manage Your Account</strong>: to manage Your registration as a user of the Service.
            </li>
            <li>
              <strong>For the performance of a contract</strong>: the development, compliance and undertaking of the
              purchase contract for the products, items or services You have purchased.
            </li>
            <li>
              <strong>To contact You</strong>: To contact You by email, telephone calls, SMS, or other equivalent forms
              of electronic communication.
            </li>
            <li>
              <strong>To provide You</strong> with news, special offers and general information about other goods,
              services and events.
            </li>
            <li>
              <strong>To manage Your requests</strong>: To attend and manage Your requests to Us.
            </li>
          </ul>

          <h3 className="text-xl font-semibold mb-4 text-white">Security of Your Personal Data</h3>
          <p className="text-gray-300 mb-8">
            The security of Your Personal Data is important to Us, but remember that no method of transmission over the
            Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable
            means to protect Your Personal Data, We cannot guarantee its absolute security.
          </p>

          <h2 className="text-2xl font-bold mb-4 text-white">Children's Privacy</h2>
          <p className="text-gray-300 mb-8">
            Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable
            information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your
            child has provided Us with Personal Data, please contact Us.
          </p>

          <h2 className="text-2xl font-bold mb-4 text-white">Contact Us</h2>
          <p className="text-gray-300 mb-4">If you have any questions about this Privacy Policy, You can contact us:</p>
          <p className="text-gray-300">
            By email:{" "}
            <a href="mailto:pullupapp2025@gmail.com" className="text-blue-400 hover:text-blue-300">
              pullupapp2025@gmail.com
            </a>
          </p>
        </div>
      </div>
    </div>
  )
}
